import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SENDGRID_API_KEY = Deno.env.get('SENDGRID_API_KEY')!;
const EMAIL_FROM = Deno.env.get('EMAIL_FROM') || 'offers@brandonstoyota.com';
const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface EmailRequest {
  offerId: string;
  recipientEmail: string;
  recipientName?: string;
  offerText: string;
  vehicleInfo?: string;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    // Validate required environment variables
    if (!SENDGRID_API_KEY) {
      throw new Error('SENDGRID_API_KEY environment variable not set');
    }
    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error('Supabase environment variables not set');
    }

    // Parse request body
    const { offerId, recipientEmail, recipientName, offerText, vehicleInfo }: EmailRequest = await req.json();

    // Validate required fields
    if (!offerId || !recipientEmail || !offerText) {
      return new Response(
        JSON.stringify({ success: false, error: 'Missing required fields: offerId, recipientEmail, offerText' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create Supabase client with service role key
    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // Build email subject
    const subject = vehicleInfo ? `Your Vehicle Offer - ${vehicleInfo}` : 'Your Vehicle Offer';

    // Build HTML email content
    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${subject}</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
  <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
    <h1 style="color: white; margin: 0; font-size: 28px;">Your Vehicle Offer</h1>
    ${vehicleInfo ? `<p style="color: rgba(255,255,255,0.9); margin: 10px 0 0 0; font-size: 16px;">${vehicleInfo}</p>` : ''}
  </div>

  <div style="background: #ffffff; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 10px 10px;">
    <h2 style="color: #1f2937; margin-top: 0;">Hello ${recipientName || 'there'},</h2>

    <p style="color: #4b5563; font-size: 16px;">
      Thank you for submitting your vehicle offer through Brandon's Calculator. Here are the details:
    </p>

    <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin: 20px 0; font-family: 'Courier New', monospace; font-size: 13px; white-space: pre-wrap; overflow-x: auto;">${offerText}</div>

    <div style="background: #eff6ff; border-left: 4px solid #3b82f6; padding: 15px; margin: 20px 0; border-radius: 4px;">
      <p style="margin: 0; color: #1e40af; font-size: 14px;">
        <strong>What happens next?</strong><br>
        A dealer will review your offer and typically responds within the hour. They may contact you via phone or email to discuss next steps.
      </p>
    </div>

    <p style="color: #6b7280; font-size: 14px; margin-top: 30px;">
      If you have any questions or need to make changes to your offer, please reply to this email.
    </p>

    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;">

    <p style="color: #9ca3af; font-size: 12px; text-align: center; margin: 0;">
      Generated by <strong>Brandon's Calculator</strong><br>
      Your trusted auto financing calculator
    </p>
  </div>
</body>
</html>
    `.trim();

    // Plain text version (fallback)
    const textContent = `
Hello ${recipientName || 'there'},

Thank you for submitting your vehicle offer through Brandon's Calculator.

${vehicleInfo ? `Vehicle: ${vehicleInfo}\n` : ''}
Your Offer Details:
${offerText}

What happens next?
A dealer will review your offer and typically responds within the hour. They may contact you via phone or email to discuss next steps.

If you have any questions or need to make changes to your offer, please reply to this email.

---
Generated by Brandon's Calculator
Your trusted auto financing calculator
    `.trim();

    // Send email via SendGrid API
    const sendGridResponse = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${SENDGRID_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        personalizations: [{
          to: [{ email: recipientEmail, name: recipientName || recipientEmail }]
        }],
        from: {
          email: EMAIL_FROM,
          name: "Brandon's Calculator"
        },
        subject: subject,
        content: [
          { type: 'text/plain', value: textContent },
          { type: 'text/html', value: htmlContent }
        ]
      })
    });

    // Extract SendGrid message ID from response headers
    const messageId = sendGridResponse.headers.get('x-message-id');
    const sendGridStatus = sendGridResponse.ok;
    let errorMessage = null;

    if (!sendGridStatus) {
      errorMessage = await sendGridResponse.text();
      console.error('SendGrid API error:', errorMessage);
    }

    // Log to email_logs table
    const { error: logError } = await supabase.from('email_logs').insert({
      offer_id: offerId,
      recipient_email: recipientEmail,
      recipient_name: recipientName || null,
      subject: subject,
      status: sendGridStatus ? 'sent' : 'failed',
      sendgrid_message_id: messageId,
      error_message: errorMessage,
      sent_at: sendGridStatus ? new Date().toISOString() : null,
    });

    if (logError) {
      console.error('Error logging email send:', logError);
      // Don't fail the request if logging fails
    }

    // Update offer status to 'sent' if email succeeded
    if (sendGridStatus) {
      const { error: updateError } = await supabase
        .from('customer_offers')
        .update({
          status: 'sent',
          updated_at: new Date().toISOString()
        })
        .eq('id', offerId);

      if (updateError) {
        console.error('Error updating offer status:', updateError);
        // Don't fail the request if status update fails
      }
    }

    // Return success/failure response
    return new Response(
      JSON.stringify({
        success: sendGridStatus,
        messageId: messageId,
        error: errorMessage
      }),
      {
        status: sendGridStatus ? 200 : 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );

  } catch (error: any) {
    console.error('Unexpected error in send-email function:', error);
    return new Response(
      JSON.stringify({
        success: false,
        error: error.message || 'Internal server error'
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    );
  }
});
